### PR TITLE
pin entries

### PR DESCRIPTION
**Pull request by shamb0t**
The latest `ipfs` enables garbage collection by default, this PR adds the option to pin content (set to true by default)

### CODE REVIEW

**Comment by aphelionz** [comment]
@shamb0t Doing some testing on this one, just in the node REPL:

```
> const IPFS = require('ipfs')
> const io = require('./index')

> const ipfs = new IPFS()
Swarm listening on /ip4/127.0.0.1/tcp/14002/ipfs/QmRuYFi7JWsy95amGNv7jokMZGEYGGzqRSWJoAjKRg1FnL
Swarm listening on /ip4/10.1.10.115/tcp/14002/ipfs/QmRuYFi7JWsy95amGNv7jokMZGEYGGzqRSWJoAjKRg1FnL
Swarm listening on /p2p-circuit/ipfs/QmRuYFi7JWsy95amGNv7jokMZGEYGGzqRSWJoAjKRg1FnL
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/14002/ipfs/QmRuYFi7JWsy95amGNv7jokMZGEYGGzqRSWJoAjKRg1FnL
Swarm listening on /p2p-circuit/ip4/10.1.10.115/tcp/14002/ipfs/QmRuYFi7JWsy95amGNv7jokMZGEYGGzqRSWJoAjKRg1Fn


> io
{ read: [Function: read], write: [Function: write] }


> io.write(ipfs, 'dag-pb', { test: 'test' }).then(console.log)
(node:436) UnhandledPromiseRejectionWarning: TypeError: node.serialize is not a function
    at Object.serialize (/home/mark/Projects/orbitdb/orbit-db-io/node_modules/ipld/node_modules/ipld-dag-pb/src/util.js:36:17)
    at IPLDResolver.put (/home/mark/Projects/orbitdb/orbit-db-io/node_modules/ipld/src/index.js:191:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is that correct?

Also, w/r/t pinning: does cbor automatically pin and we only need to worry about protobuf?

**Comment by shamb0t** [comment]
@aphelionz thanks! There was indeed an issue with the DagPB constructor. Fixed [here](https://github.com/orbitdb/orbit-db-io/pull/8/files#diff-168726dbe96b3ce427e7fedce31bb0bcR36)

I believe neither are pinned by default and we need to explicitly pin any entry not intended for garbage collected

**Comment by aphelionz** [comment]
Works better for me but I'm still not seeing the `dag-cbor` hash pinned if I run `io.write` followed by `ipfs.pin.ls`

```
> io.write(ipfs, 'dag-cbor', 'xxx').then(console.log)
zdpuAtfWXrBBassEnUCtdRnZ3ApiZUwL3kbMRPdJzEBgb6ZwE

> ipfs.pin.ls
> ipfs.pin.ls().then(console.log)
[ { type: 'recursive',
    hash: 'QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr' },
  { type: 'recursive',
    hash:
     'bafyreid2pa2ofqrkmfcmbwkp3kojwtomdwypxe7zhumm7bhi2ygwzx2vce' },
  { type: 'indirect',
    hash: 'QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V' },
  { type: 'indirect',
    hash: 'QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC' },
  { type: 'indirect',
    hash: 'QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y' },
  { type: 'indirect',
    hash: 'QmdncfsVm2h5Kqq9hPmU7oAVX2zTSVP3L869tgTbPYnsha' },
  { type: 'indirect',
    hash: 'QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7' },
  { type: 'indirect',
    hash: 'QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB' },
  { type: 'indirect',
    hash: 'QmQ5vhrL7uv6tuoN9KeVBwd4PwfQkXdVVmDLUZuTNxqgvm' },
  { type: 'indirect',
    hash: 'QmciSU8hfpAXKjvK5YLUSwApomGSWN5gFbP4EpDAEzu2Te' },
  { type: 'indirect',
    hash: 'QmQN88TEidd3RY2u3dpib49fERTDfKtDpvxnvczATNsfKT' },
  { type: 'indirect',
    hash: 'QmYE7xo6NxbHEVEHej1yzxijYaNY51BaeKxjXxn6Ssa6Bs' } ]

> io.write(ipfs, 'dag-pb', 'xxx').then(console.log)
QmX9hEN2aT3PXGhsoqcfF3DkY1LBpmeF6MYaSMonNoE3Co

ipfs.pin.ls().then(console.log)
[ { type: 'recursive',
    hash: 'QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr' },
  { type: 'recursive',
    hash:
     'bafyreid2pa2ofqrkmfcmbwkp3kojwtomdwypxe7zhumm7bhi2ygwzx2vce' },
  { type: 'recursive',
    hash: 'QmX9hEN2aT3PXGhsoqcfF3DkY1LBpmeF6MYaSMonNoE3Co' },
  { type: 'indirect',
    hash: 'QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y' },
  { type: 'indirect',
    hash: 'QmdncfsVm2h5Kqq9hPmU7oAVX2zTSVP3L869tgTbPYnsha' },
  { type: 'indirect',
    hash: 'QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V' },
  { type: 'indirect',
    hash: 'QmegvLXxpVKiZ4b57Xs1syfBVRd8CbucVHAp7KpLQdGieC' },
  { type: 'indirect',
    hash: 'QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7' },
  { type: 'indirect',
    hash: 'QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB' },
  { type: 'indirect',
    hash: 'QmQ5vhrL7uv6tuoN9KeVBwd4PwfQkXdVVmDLUZuTNxqgvm' },
  { type: 'indirect',
    hash: 'QmciSU8hfpAXKjvK5YLUSwApomGSWN5gFbP4EpDAEzu2Te' },
  { type: 'indirect',
    hash: 'QmQN88TEidd3RY2u3dpib49fERTDfKtDpvxnvczATNsfKT' },
  { type: 'indirect',
    hash: 'QmYE7xo6NxbHEVEHej1yzxijYaNY51BaeKxjXxn6Ssa6Bs' } ]
```

**Comment by shamb0t** [comment]
@aphelionz the CID v1 hashes listed in `ipfs.pin.ls` are base32 hashes. You need to convert your CID to base32 which is `bafyreid2pa2ofqrkmfcmbwkp3kojwtomdwypxe7zhumm7bhi2ygwzx2vce`

**Pull request merged**
